// acerola/dashboard/client/src/lib/ui/primitives/column-chart.component.svelte
<script lang="ts" module>
  import type { ChartSlice } from '$lib/utils/chart-slice.util';

  /**
   * Coluna — para comparar quantidades entre categorias (por responsável, por tipo).
   *
   * **Sem legenda** (uma série só; legenda de uma série é ruído), **o valor escrito acima de
   * cada coluna** (no lugar de obrigar a estimar pela altura) e **clique na coluna abrindo o
   * detalhamento**. Sem eixo Y: com o número em cima de cada coluna, a escala à esquerda não
   * acrescenta nada e come largura.
   */
  export type ColumnChartProps = {
    data: {
      slices: ChartSlice[];
      /** O nome da série no popover — "Tarefas: 8". Mesmo motivo da rosca. */
      seriesLabel: string;
    };
    state?: { isLoading?: boolean };
    ui?: { emptyLabel?: string };
    actions?: { onSelect?: (label: string) => void };
  };

  /** Rótulo longo cortado no eixo; o nome inteiro continua no tooltip. */
  function shorten(label: string): string {
    return label.length > 14 ? `${label.slice(0, 13)}…` : label;
  }

  const PADDING = { top: 36, right: 14, left: 14, bottom: 64 };
  const BAR_RADIUS = 4;
</script>

<script lang="ts">
  import { colorOfSlice } from '$lib/utils/chart-slice.util';

  /* O prop precisa de outro nome aqui dentro: um binding local chamado `state` faz o
     compilador ler `$state(...)` como inscrição numa store `state`, em vez da rune. */
  let { data, state: chartState, ui, actions }: ColumnChartProps = $props();

  // Tooltip state
  let tooltipSlice: ChartSlice | null = $state(null);
  let tooltipX = $state(0);
  let tooltipY = $state(0);

  let svgWidth = $state(0);
  let svgHeight = $state(0);

  const chartW = $derived(Math.max(1, svgWidth - PADDING.left - PADDING.right));
  const chartH = $derived(Math.max(1, svgHeight - PADDING.top - PADDING.bottom));

  const maxValue = $derived(Math.max(...data.slices.map((s) => s.value), 1));
  const barWidth = $derived(Math.max(4, chartW / Math.max(data.slices.length, 1) - 8));

  type BarInfo = {
    slice: ChartSlice;
    color: string;
    x: number;
    barY: number;
    barH: number;
    cx: number;
  };

  const bars = $derived<BarInfo[]>(
    data.slices.map((slice, i) => {
      const slotW = chartW / data.slices.length;
      const cx = PADDING.left + slotW * i + slotW / 2;
      const barH = Math.max(2, (slice.value / maxValue) * chartH);
      const barY = PADDING.top + chartH - barH;
      const color = colorOfSlice(slice.label, i);
      return { slice, color, x: cx - barWidth / 2, barY, barH, cx };
    }),
  );

  // pill width: min 20px, based on text length
  function pillWidth(text: string): number {
    return Math.max(20, text.length * 6.5 + 12);
  }

  function handleBarClick(slice: ChartSlice) {
    actions?.onSelect?.(slice.label);
  }
</script>

<svelte:options runes={true} />

{#if chartState?.isLoading}
  <div class="h-full w-full animate-pulse rounded-lg bg-slate-100"></div>
{:else if data.slices.length === 0}
  <p class="flex h-full items-center justify-center text-xs text-slate-400">
    {ui?.emptyLabel ?? 'Sem dados para mostrar'}
  </p>
{:else}
  <div class="relative h-full w-full">
    <svg
      bind:clientWidth={svgWidth}
      bind:clientHeight={svgHeight}
      class="h-full w-full overflow-visible"
      aria-label={data.seriesLabel}
      role="img"
    >
      {#each bars as bar (bar.slice.label)}
        {@const text = String(bar.slice.value)}
        {@const pw = pillWidth(text)}
        <!-- Bar column -->
        <g
          role={actions?.onSelect ? 'button' : undefined}
          tabindex={actions?.onSelect ? 0 : undefined}
          aria-label="{bar.slice.label}: {bar.slice.value}"
          style="cursor: {actions?.onSelect ? 'pointer' : 'default'}"
          onclick={() => handleBarClick(bar.slice)}
          onkeydown={(e) => e.key === 'Enter' && handleBarClick(bar.slice)}
          onmouseenter={(e) => {
            tooltipSlice = bar.slice;
            tooltipX = e.clientX;
            tooltipY = e.clientY;
          }}
          onmouseleave={() => (tooltipSlice = null)}
        >
          <rect
            x={bar.x}
            y={bar.barY}
            width={barWidth}
            height={bar.barH}
            rx={BAR_RADIUS}
            ry={BAR_RADIUS}
            fill={bar.color}
          />

          <!-- Value badge above bar -->
          <g class="pointer-events-none">
            <rect
              x={bar.cx - pw / 2}
              y={bar.barY - 20}
              width={pw}
              height={16}
              rx={8}
              fill={bar.color}
            />
            <text
              x={bar.cx}
              y={bar.barY - 12}
              text-anchor="middle"
              dominant-baseline="middle"
              class="fill-white text-[10px] font-semibold"
              font-size="10"
              font-weight="600"
              fill="white"
            >
              {text}
            </text>
          </g>

          <!-- X-axis label -->
          <text
            x={bar.cx}
            y={PADDING.top + chartH + 18}
            text-anchor="end"
            transform="rotate(-30, {bar.cx}, {PADDING.top + chartH + 18})"
            class="fill-slate-500 text-[11px]"
            font-size="11"
            fill="#64748b"
          >
            {shorten(bar.slice.label)}
          </text>
        </g>
      {/each}
    </svg>

    <!-- Tooltip -->
    {#if tooltipSlice}
      <div
        class="bg-card pointer-events-none fixed z-50 rounded-xl px-3 py-2.5 text-xs shadow-lg ring-1 ring-black/5"
        style="left: {tooltipX + 12}px; top: {tooltipY - 8}px;"
      >
        <p class="font-semibold">{tooltipSlice.label}</p>
        <p class="text-muted-foreground">{data.seriesLabel}: {tooltipSlice.value}</p>
      </div>
    {/if}
  </div>
{/if}

// acerola/client/src/lib/ui/primitives/column-chart.component.tsx
import { Bar, BarChart, Cell, LabelList, XAxis } from 'recharts';

import { ChartContainer, ChartTooltip, ChartTooltipContent } from '../../vendor/ui/chart';
import { type ChartSlice, colorOfSlice } from '../../utils/chart-slice.util';

/**
 * Coluna — para comparar quantidades entre categorias (por responsável, por tipo).
 *
 * **Sem legenda** (uma série só; legenda de uma série é ruído), **o valor escrito acima de
 * cada coluna** (no lugar de obrigar a estimar pela altura) e **clique na coluna abrindo o
 * detalhamento**. Sem eixo Y: com o número em cima de cada coluna, a escala à esquerda não
 * acrescenta nada e come largura.
 */
export type ColumnChartProps = {
  data: {
    slices: ChartSlice[];
    /** O nome da série no popover — "Tarefas: 8". Mesmo motivo da rosca. */
    seriesLabel: string;
  };
  state?: { isLoading?: boolean };
  ui?: { emptyLabel?: string };
  actions?: { onSelect?: (label: string) => void };
};

export function ColumnChart({ data, state, ui, actions }: ColumnChartProps) {
  if (state?.isLoading) {
    return <div className="h-full w-full animate-pulse rounded-lg bg-slate-100" />;
  }

  if (data.slices.length === 0) {
    return (
      <p className="flex h-full items-center justify-center text-xs text-slate-400">
        {ui?.emptyLabel ?? 'Sem dados para mostrar'}
      </p>
    );
  }

  return (
    <ChartContainer
      config={{ value: { label: data.seriesLabel } }}
      className="aspect-auto h-full w-full"
    >
      {/* Margem lateral maior que o normal: o selo do valor é mais largo que o número
          sozinho, e nas colunas da ponta ele passava da borda do gráfico sem essa folga.
          Margem de baixo também maior: some com a folga que faltava pro rótulo comprido do
          eixo (girado -30°) não vazar por baixo da área do SVG — o `height` do `XAxis` reserva
          espaço para o texto girado, mas sem margem nenhuma o pé do texto encostava na borda
          de baixo e cortava. */}
      <BarChart data={data.slices} margin={{ top: 24, right: 14, left: 14, bottom: 12 }}>
        {/* Mesmo contêiner arredondado e com sombra macia que a rosca usa — os dois
            popovers do dashboard têm que parecer a mesma peça. `labelFormatter` troca o
            título pelo NOME da fatia em vez do rótulo genérico da série: sem ele, o topo do
            popover ficava em branco (o cruzamento de `labelKey`/`config` não resolvia
            sozinho) e só a linha "Tarefas: 6" aparecia — sem dizer de QUAL categoria. */}
        <ChartTooltip
          cursor={{ fill: 'var(--color-muted)' }}
          content={
            <ChartTooltipContent
              nameKey="value"
              labelFormatter={(_, tooltipPayload) =>
                (tooltipPayload?.[0]?.payload as ChartSlice | undefined)?.label ?? ''
              }
              className="bg-card rounded-xl border-none px-3 py-2.5 shadow-lg ring-1 ring-black/5"
            />
          }
        />
        <XAxis
          dataKey="label"
          tickLine={false}
          axisLine={false}
          interval={0}
          height={64}
          angle={-30}
          textAnchor="end"
          tickFormatter={(label: string) => shorten(label)}
        />
        <Bar
          dataKey="value"
          radius={[4, 4, 0, 0]}
          onClick={(bar: unknown) => actions?.onSelect?.(readLabel(bar))}
          className={actions?.onSelect ? 'cursor-pointer' : undefined}
        >
          {data.slices.map((slice, index) => (
            <Cell key={slice.label} fill={colorOfSlice(slice.label, index)} />
          ))}
          {/* Selo na MESMA cor da coluna — não uma cor genérica só pra ele — pra ler como
              parte da própria coluna, não como uma etiqueta colada em cima. */}
          <LabelList
            dataKey="value"
            position="top"
            offset={12}
            content={(props: unknown) => (
              <ColumnValueBadge {...(props as ColumnValueBadgeProps)} slices={data.slices} />
            )}
          />
        </Bar>
      </BarChart>
    </ChartContainer>
  );
}

/** Rótulo longo cortado no eixo; o nome inteiro continua no tooltip. */
function shorten(label: string): string {
  return label.length > 14 ? `${label.slice(0, 13)}…` : label;
}

function readLabel(bar: unknown): string {
  const payload = bar as { label?: string; payload?: { label?: string } };

  return payload.label ?? payload.payload?.label ?? '';
}

type ColumnValueBadgeProps = { x: number; y: number; width: number; value: number; index: number };

/**
 * O selo do valor, desenhado à mão — SVG puro, porque `LabelList` só aceita marcação SVG
 * (`<g>`, `<rect>`, `<text>`), não um componente HTML qualquer por cima do gráfico.
 *
 * Largura calculada pelo tamanho do texto: um selo de largura fixa ou sobra vazio atrás de
 * "1" ou corta o "6" de duas colunas de dois dígitos — nenhuma das opções serve pras duas
 * pontas que a mesma coluna precisa cobrir.
 *
 * A cor vem de `colorOfSlice(slices[index].label, index)` — a MESMA conta que colore a
 * `<Cell>` da coluna logo abaixo — para o selo nunca destoar da coluna que ele rotula.
 */
function ColumnValueBadge({
  x,
  y,
  width,
  value,
  index,
  slices,
}: ColumnValueBadgeProps & { slices: ChartSlice[] }) {
  const text = String(value);
  const pillWidth = Math.max(20, text.length * 6.5 + 12);
  const cx = x + width / 2;
  const fill = colorOfSlice(slices[index]?.label ?? '', index);

  return (
    <g className="pointer-events-none">
      <rect x={cx - pillWidth / 2} y={y - 16} width={pillWidth} height={16} rx={8} fill={fill} />
      <text
        x={cx}
        y={y - 8}
        textAnchor="middle"
        dominantBaseline="middle"
        className="fill-white text-[10px] font-semibold"
      >
        {text}
      </text>
    </g>
  );
}
