// acerola/client/src/lib/ui/primitives/select-field.component.tsx
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '../../vendor/ui/select';
import { cn } from '../../utils/cn.util';

export type SelectFieldOption = { value: string; label: string };

/**
 * `<select>` nativo trocado pelo Select do shadcn/ui — mesmo comportamento (uma opção,
 * `onChange` com o valor), mas o menu e o destaque de foco ficam iguais em qualquer
 * navegador, em vez de herdar o estilo do sistema operacional.
 *
 * Radix não aceita `value=""` num item (é o sentinel dele para "nenhuma seleção"), então
 * a opção "vazia" (Todos, Não preenchido...) troca de string vazia para `EMPTY_VALUE` só
 * aqui dentro. Quem chama continua vendo `''` — o desvio não vaza para o resto do app.
 */
export type SelectFieldProps = {
  data: { value: string; options: SelectFieldOption[] };
  ui?: { placeholder?: string; ariaLabel?: string; className?: string };
  state?: { isDisabled?: boolean };
  actions: { onChange: (value: string) => void };
};

const EMPTY_VALUE = '__empty__';

export function SelectField({ data, ui, state, actions }: SelectFieldProps) {
  return (
    <Select
      value={data.value === '' ? EMPTY_VALUE : data.value}
      onValueChange={(value) => actions.onChange(value === EMPTY_VALUE ? '' : value)}
      disabled={state?.isDisabled}
    >
      <SelectTrigger
        aria-label={ui?.ariaLabel}
        className={cn('h-auto rounded-sm py-2 text-sm', ui?.className)}
      >
        <SelectValue placeholder={ui?.placeholder} />
      </SelectTrigger>
      <SelectContent>
        {data.options.map((option) => (
          <SelectItem key={option.value || EMPTY_VALUE} value={option.value || EMPTY_VALUE}>
            {option.label}
          </SelectItem>
        ))}
      </SelectContent>
    </Select>
  );
}

// acerola/dashboard/client/src/lib/components/select-field/select-field.svelte
<script lang="ts" module>
  /**
   * Campo de seleção — o mesmo em filtro e em formulário.
   *
   * O `EMPTY_VALUE` abaixo resolve um conflito entre duas regras: para o sistema, "nenhum
   * filtro" é a string vazia; para o componente baixado, valor vazio significa "nada
   * selecionado", e ele então mostra o placeholder em vez da opção "Todos". Traduzir a
   * string vazia para uma sentinela na entrada e de volta na saída mantém a opção visível
   * sem contaminar o contrato de quem usa o campo, que continua recebendo `''`.
   */
  export type SelectFieldOption = { value: string; label: string };

  export type SelectFieldProps = {
    data: { value: string; options: SelectFieldOption[] };
    ui?: { placeholder?: string; ariaLabel?: string; className?: string };
    state?: { isDisabled?: boolean };
    actions: { onChange: (value: string) => void };
  };

  const EMPTY_VALUE = '__empty__';
</script>

<script lang="ts">
  import {
    Select,
    SelectContent,
    SelectItem,
    SelectTrigger,
    SelectValue,
  } from '$lib/components/ui/select';
  import { cn } from '$lib/utils/cn.util';

  let { data, ui, state, actions }: SelectFieldProps = $props();

  const selectedValue = $derived(data.value === '' ? EMPTY_VALUE : data.value);
</script>

<Select
  type="single"
  value={selectedValue}
  onValueChange={(val: string | undefined) => {
    if (val !== undefined) {
      actions.onChange(val === EMPTY_VALUE ? '' : val);
    }
  }}
  disabled={state?.isDisabled}
>
  <SelectTrigger
    aria-label={ui?.ariaLabel}
    class={cn('h-auto rounded-sm py-2 text-sm', ui?.className)}
  >
    <SelectValue placeholder={ui?.placeholder} />
  </SelectTrigger>
  <SelectContent>
    {#each data.options as option (option.value || EMPTY_VALUE)}
      <SelectItem value={option.value || EMPTY_VALUE} label={option.label}>
        {option.label}
      </SelectItem>
    {/each}
  </SelectContent>
</Select>
